### ISSUE TITLE
Extended features clarification

### ISSUE THREAD

**Issue by SantjagoCorkez** [RubinCarter/gitflow4idea-plus#5]
* **I'm submitting a ...**
Documentation request

Extended features versus original plugin are stated in the README. What are those extended features?

**Comment by RubinCarter** [comment]
@SantjagoCorkez Since the version maintained by the original author has not been updated for a long time, I like this plugin very much like you, so I decided to maintain this plugin. No special features have been added so far, just some bug fixes. Of course, you are very welcome to provide some feature suggestions

**Comment by SantjagoCorkez** [comment]
I've looked thoroughly through the commit log into this project:
- what's the purpose of adding a file, deleting a file, adding a change, removing that change and so on?
- what's in the binary jar in `gradle/wrapper` folder which was not present in the original plugin?

**Comment by RubinCarter** [comment]
@SantjagoCorkez hi, there are the following two plans in progress, maybe the code submission is not standardized enough
1. A feature is being added to initialize gitflow based on file configuration
2. Automatically generate installation package based on github actions
